### ISSUE TITLE
Broad page unaccessible

### ISSUE THREAD

**Issue by KoichiHashikawa** [kkdey/GSSG#26]
Hi @kkdey 
It seems that https://alkesgroup.broadinstitute.org/ is not accessible. Is the website under construction or renewed somewhere?
thanks.
Koichi

**Comment by kkdey** [comment]
@KoichiHashikawa It should be accessible now. It was down for some maintenance issues.

**Comment by KoichiHashikawa** [comment]
Thank you!

**Comment by KoichiHashikawa** [comment]
@kkdey 
Hello Kushal,

Is the https://alkesgroup.broadinstitute.org/ under maintenance now? It seems it is not accessible for a week or so.

Thank you!

**Comment by kkdey** [comment]
@KoichiHashikawa Unfortunately yes, we had to take it down because we are facing huge egress charges potentially due to batch scripts accessing and downloading the data from outside of USA. We are trying to recalibrate our folder to be able to detect such egress and block it going forward. We are probably going to move to a requester pays option. The website will be up early next week with the recalibration. Apologies for this.

**Comment by kkdey** [comment]
It should be fixed now. All the relevant data required to run sc-linker are available on the public bucket, annotations and LD scores and results can be downloaded using requester pays bucket for a very nominal fee - in cents. Thanks for your patience.
